### ISSUE TITLE
miner UI goes crazy on windows

### ISSUE THREAD

**Issue by jahshaka** [jahshaka/Studio#357]
when you hav a zoomed desktop on windows the zoom messes up the miner ui for some reason - my monitor is 4k but i am testing jahshaka with a 200% zoom in display settings 

![image from ios 3](https://user-images.githubusercontent.com/6324793/43373548-9de24ca6-93aa-11e8-9292-854b2675a902.jpg)

**Comment by iKlsR** [comment]
@willroyMyles will start the new UI so closing this for now.
