### ISSUE TITLE
miner text and pool light misleading

### ISSUE THREAD

**Issue by jahshaka** [jahshaka/Studio#367]
the miner text is very misleading... and lights for pool dont make sense.... they need to work togeather.

1. gpu set to mine (pool light should be RED)
2. connecting to pool (pool light should be orange)
3. mining (pool light should be green)

**Comment by jahshaka** [comment]
currently when you click start it says mining - its not mining its connecting to the pool...

**Comment by willroyMyles** [comment]
Fixed

**Comment by njbrown** [comment]
There's still one more thing left before closing the issue. The miner text should say "Mining" once actual mining has begun, there is a 10 second delay.

**Comment by njbrown** [comment]
fixed
