### ISSUE TITLE
usres can edit in player in VR

### ISSUE THREAD

**Issue by jahshaka** [jahshaka/Studio#410]
users in the player are not supposed to be able to edit scenes just move around inside the scene. this works when not in VR but when in VR with Touch you can edit and destroy scenes in the player.

**Comment by jahshaka** [comment]
editing using the touch should only work in the editor - meaning no red lines from hands to objects please they destroy all demos. or at least no HALO in player ? not sure whats best

for the player i would assume you point at a object then click to get the red selection bar or something but the experiences is quite horrible right now.. as everything has a red halo and when trying to move around a scene in the player you end up destroying it

**Comment by njbrown** [comment]
This one is a simple fix
