### ISSUE TITLE
change scenes link on desktop

### ISSUE THREAD

**Issue by jahshaka** [jahshaka/Studio#414]
the o;d link on the desktop to download worlds needs to be changed to scenes (we will fix the website with a redirect and change of slug)

so change this link when they click downlaod scenes

https://www.jahfx.com/downloads/worlds/

to this link

https://www.jahfx.com/downloads/scenes/

will give a error on jahfx until the redirect is in place thats ok

**Comment by willroyMyles** [comment]
close
