### ISSUE TITLE
sliders for new dynamic materials

### ISSUE THREAD

**Issue by jahshaka** [jahshaka/Studio#427]
we need to expose sliders / inputs in the materials mox for new dynamic materials - for eg i want to change the color of my distortion shader, and the roughness of the effect as well as the resolution of the effect

different materials will have different inputs - for eg we need a water material for drag and drop that will have wave density so this needs to be dynamically set on a per material basis... with the material passing the valuse defined to the shader ?

would be cool to also then use equations to drive these so for eg the distortion shader could respon to audio input ?

**Comment by iKlsR** [comment]
This isn't related to anything really, the person who wrote the shader can add the options. Not a technical issue, use the art channel.
