### ISSUE TITLE
material request : grass

### ISSUE THREAD

**Issue by jahshaka** [jahshaka/Studio#432]
can we create a standalone grass material / shader that creates realitic looking grass like fortnight

![image](https://user-images.githubusercontent.com/6324793/44634921-c84a3200-a99f-11e8-9f51-6ca3e4878f53.png)

would prefer this to 3d object based grass - will be much more realistic if procedurally generated

**Comment by iKlsR** [comment]
Please only use *issues* for **technical** related things. Use the art channel on slack.
