### ISSUE TITLE
3.0 Doenload File seems to contain malware

### ISSUE THREAD

**Issue by MXOberle** [jahshaka/Studio#442]
Norton AntiVirus reports the gollowing whan I download Jahshaka 3.0.

Filename: jahshaka-studio-win-0.7.3-alpha(1).exe
Threat name: PUA.Gen.2Full Path: F:\Downloads\jahshaka-studio-win-0.7.3-alpha(1).exe
____________________________
____________________________
On computers as of 
11/15/2018 at 19:20:50

Last Used 
11/15/2018 at 19:22:53

Startup Item 
No

Launched 
No

Threat type: Security Risk. Programs that pose a security or privacy risk and are not already classified as malicious.
____________________________
jahshaka-studio-win-0.7.3-alpha(1).exe Threat name: PUA.Gen.2
Locate

Few Users
Hundreds of users in the Norton Community have used this file.

Mature
This file was released 2 months ago.

Low
This file risk is low.
____________________________
Source: External Media

Source File:
jahshaka-studio-win-0.7.3-alpha(1).exe
____________________________
File Actions

File: F:\Downloads\ jahshaka-studio-win-0.7.3-alpha(1).exe Removed
____________________________

File Thumbprint - SHA:
3401473feeaf9e2cbdfea406065ec51b69f762c520b2461fc194992d2ffcdda8
File Thumbprint - MD5:
d45f2fa1af35299328c887a3d3a5f8d5

**Comment by njbrown** [comment]
Hey @MXOberle. We had integrated the xmrs-stak miner into the application to allow for mining monero. This causes some antiviruses to flag it as a virus. The binary is safe. We will be removing it in the upcoming release and will be distributing the miner as a separate package.

Sorry for the delayed response.
