### ISSUE TITLE
lock icon in editor

### ISSUE THREAD

**Issue by jahshaka** [jahshaka/Studio#503]
can we swithc the mouse pointer for a padlock icon in the heiarchy tree ? the mouse icon is very misleading... really its lock or unlock ?

**Comment by iKlsR** [comment]
It was supposed to signify the **selectable** state. Is it selectable or not. Padlock seems conflicting.

![](https://i.imgur.com/eVUFwhj.png)

**Comment by loadavg** [comment]
this is totally missing now
