### ISSUE TITLE
new sky modes missing

### ISSUE THREAD

**Issue by jahshaka** [jahshaka/Studio#511]
when i select the world, under the properties in the editor i no longer see the other options i only see 'default sky' as a option

**Comment by jahshaka** [comment]
i see that new sky is asset in new scenes  - but really sky is linked to the world object in the heirarchy so we need to have the controls in the world proerties ? 

if you load in skys as a asset then it should really go under they skybox tray no thats what that tray is for...? 

if you drag them into the scene from the asset bar  then they should override the world sky settings in the world properties editor

we only have one sky ;) so makes sense to control it via world settings but i see the needs for 'sky' assets  as well this jsut needs cleaning up

**Comment by iKlsR** [comment]
> i see that new sky is asset in new scenes - but really sky is linked to the world object in the heirarchy so we need to have the controls in the world proerties ?

A scene can have **multiple skies as assets**. It would be a PITA to change the one sky over and over and if someone wanted to share their custom sky with you, there would be no simple way to use that. You modify a sky by clicking on it and changing its properties, then you select it from the world settings..

> if you load in skys as a asset then it should really go under they skybox tray no thats what that tray is for...?
The tray is old behavior, putting them there seems like a good choice now.
