### ISSUE TITLE
rename scenes in menubar

### ISSUE THREAD

**Issue by jahshaka** [jahshaka/Studio#520]
can you rename Scenes to Desktop in the main menu bar - nowhere else this is cosmetic only please! the desktop is used to manager your scenes....

so

Desktop / Player / Editor etc

I also think Editor should be after Desktop since we are a creation tool and Player is preview and testing really ?

Desktop Editor Player etc

**Comment by loadavg** [comment]
PERFECT

**Comment by loadavg** [comment]
close#
